

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false    gateway:
      routes:
      #- id : AppLoadBalancer
        #uri: http://localhost:8000   with only gateway ten make loadbalancer a separate proj
      - id : msam1
        uri: lb://msam1
        predicates:        - Path=/appm1/**
      #- id : FeatureLoadBalancer
        #uri: http://localhost:8001
      - id : msafeature
        uri: lb://msafeature
        predicates:        - Path=/ftre/*
      - id : secJWT
        uri: lb://secJWT
        predicates:
        - Path=/authN
      discovery:
        locator:
           enabled: true
           lower-case-service-id: true