

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false    gateway:
      routes:
      #- id : AppLoadBalancer
        #uri: http://localhost:8000   with only gateway then make loadbalancer a separate proj
      - id : msam1
        uri: lb://msam1
        predicates:        - Path=/appm1/**
      #- id : FeatureLoadBalancer
        #uri: http://localhost:8001
      - id : msafeature
        uri: lb://msafeature
        predicates:        - Path=/ftre/*
      - id : secJWT
        uri: lb://secJWT
        predicates:
        - Path=/authN
      - id : thyme
        uri: lb://thyme
        predicates:
        - Path=/thy1/**
      - id : thyme2
        uri: lb://thyme2
        predicates:
        - Path=/thy2/**
      #- id : autenticationServ
       # uri: http://localhost:8080
       # predicates:
       # - Path=/authenticate
      discovery:
        locator:
           enabled: true
           lower-case-service-id: true