resilience4j.circuitbreaker:
    configs:
       default:
            registerHealthIndicator: true  #localhost:8080/actuator/health
            register-health-indicator: true
            sliding-window-size: 10
            permitted-number-of-calls-in-half-open-state: 3
            sliding-window-type: TIME_BASED
            minimum-number-of-calls: 20
            wait-duration-in-open-state: 50s
            failure-rate-threshold: 50
            event-consumer-buffer-size: 10
            #slidingWindowSize: 10
            #permittedNumberOfCallsInHalfOpenState: 3
            #slidingWindowType: TIME_BASED
            #minimumNumberOfCalls: 20
            #waitDurationInOpenState: 50s
            #failureRateThreshold: 50
            #eventConsumerBufferSize: 10
            #recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate
            recordExceptions:
              - org.springframework.web.client.HttpServerErrorException
              - java.io.IOException
              - java.util.concurrent.TimeoutException
              #- org.springframework.web.client.ResourcrAccessException
            #ignore-exceptions:
              #- io.github.resilience4j.circuitbreaker.IgnoredException
            #retryExceptions:
            #  - java.lang.IllegalArgumentException
            ring-buffer-size-in-closed-state: 5
            ring-buffer-size-in-half-open-state: 3           
    instances:
       msam3:
          base-config: default
            